name: Windows CI

on: [push]

jobs:
  windows-build-test:
    runs-on: windows-2019
    strategy:
      matrix:
        # C++98, C++03 and C++11 is NOT supported by MSVC 2019
        cxx-standard: ["14", "17"]
    steps:
      - name: Clone and checkout commit
        uses: actions/checkout@v1
      - name: Let CMake generate build configuration
        run: cmake -G "Visual Studio 16 2019" -DSNOWHOUSE_RUN_TESTS=0 -DSNOWHOUSE_BUILD_TESTS=1 -DSNOWHOUSE_CXX_STANDARD=C++${{ matrix.cxx-standard }} .
      - name: Build tests with MSVC and C++${{ matrix.cxx-standard }}
        run: cmake --build .
      - name: Run tests
        run: bin\Debug\snowhouse-tests.exe
